[package]
name = "lotic"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "examples/basic-usage","lotic-macros"]

[dependencies]
lotic-macros = { path = "lotic-macros" }

[workspace.dependencies]
pinocchio = "0.10.1"

