[package]
name = "lotic-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.101" }
camino = "1.1"
cargo_metadata = { version = "0.23.1" }
clap = { version = "4.5.59", features = ["derive"] }
proc-macro2 = "1.0.106"
quote = { version = "1.0.44" }
serde = "1.0.228"
serde_json = "1.0.149"
syn = { version = "2.0.116", features = ["full", "extra-traits"] }
walkdir = { version = "2.5.0" }
